### ISSUE TITLE
Why so many dependencies in the nuget package?

### ISSUE THREAD

**Issue by toburger** [TahaHachana/XTract#1]
Are Deedle, SpreadSharp and Selenium really needed to get XTract to work?
I would recommend to make two packages: one for the "core" XTract and one for the samples.

**Comment by TahaHachana** [comment]
- Deedle isn't really necessary so I'll remove it in the next release ;
- SpreadSharp is used for saving the collected data in Excel but it's possible to build this into the library;
- Selenium is used by the dynamic scrapers that drive Chrome, I plan to move them to a separate package (XTract.Dynamic) but first I need to clean the code a bit and comment it too.

**Comment by toburger** [comment]
that would be awesome!

**Comment by TahaHachana** [comment]
The new packages are still in prerelease phase, I still need to test on real world projects.
